### ISSUE TITLE
URL update

### ISSUE THREAD

**Issue by waqas767** [LiliomLab/laravel-unifonic#3]
Please update the API_URL 
From 
const API_URL = 'http://basic.unifonic.com/rest/';
To
const API_URL = 'https://el.cloud.unifonic.com/rest/';

Unifonic updated this.
current API URL is not working.

**Comment by mkwsra** [comment]
Thanks for your input, can you just tell me which branch you are using? `v1` or `master`? I guess it's master?

**Comment by mkwsra** [comment]
And can you please create a PR for this change after testing it?

**Comment by hannav23** [comment]
Is the base API_URL updated already?

**Comment by mkwsra** [comment]
No it's not, please change it in your machine, make sure it works then send me a PR and I will merge it ASAP

**Comment by waeldalol** [comment]
Yes it's working only with  'https://el.cloud.unifonic.com/rest/'; otherwise message will not be sent. Please update.

**Comment by mkwsra** [comment]
It's been changed now, thanks to @MahmoudQassass
