### ISSUE TITLE
The latest changes on master don't have a tag

### ISSUE THREAD

**Issue by muhammedkamel** [LiliomLab/laravel-unifonic#6]
The last update on the master branch which is converting the API URL from HTTP to HTTPs don't have a tag.

We need to create a new tag for it `v2.1.0` to be able to use it in my application.

Also [Unifonic will deprecate the HTTP endpoint](https://docs.unifonic.com/docs/http-deprecation-announcement-and-migration-guide) by the end of this month.

So please create a new tag for the latest changes on the master branch.

**Comment by mkwsra** [comment]
Creating the tag only won't have an effect since non of the files has been updated, so can you please send a PR the change you mentioned "from HTTP to HTTPs". so I can merge it and immediately I will create and publish a new tag

**Comment by mkwsra** [comment]
Creating the tag only won't have an effect since non of the files has been updated, so can you please send a PR the change you mentioned "from HTTP to HTTPs". so I can merge it and immediately I will create and publish a new tag

**Comment by muhammedkamel** [comment]
@mkwsra It's already done in #4. 
You can find on master the [API URL](https://github.com/multicaret/laravel-unifonic/blob/master/src/UnifonicClient.php#L9) is HTTPs while on `v2.0.0` it's using [http](https://github.com/multicaret/laravel-unifonic/blob/v2.0.0/src/UnifonicClient.php#L9).
I ensured that it's using the correct unifonic API URL [here](https://docs.unifonic.com/docs/sending-your-first-sms-via-unifonic-api) reference.

All we need now to create a new version `v2.1.0` for the latest updates on the master branch.

**Comment by muhammedkamel** [comment]
Thanks @mkwsra resolved by db28b9f
